---
# vars file for kafka

kafka_download_path: "/tmp/"
kafka_base_version: "3.1.0"
kafka_version: "2.12-3.1.0"
kafka_data_dir: "/data/kafka/"
kafka_log_dir: "/var/log/kafka/"
kafka_log_topics_dir: "/data/kafka/topics_log/"
kafka_install_dir: "/opt/kafka/"
configuration:
   port: 9092
   network_threads: 3
   disk_threads: 8
   num_partitions: 3
   so_snd_buff_bytes: 102400
   so_rcv_buff_bytes: 102400
   so_request_max_bytes: 104857600
   data_dir_recovery_threads: 1
   log_retention_hours: 24
   log_retention_bytes: 1073741824
   log_segment_bytes: 1073741824
   log_retention_check_interval: 300000
   log_cleaner_enable: false
   zk_connection_timeout: 60000